name: external_link_account
description: A Flutter iOS plugin for ExternalLinkAccount API
version: 0.0.2
repository: https://github.com/glin94/external_link_account/
issue_tracker: https://github.com/glin94/external_link_account/issues/

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^9.1.4

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ExternalLinkAccountPlugin
